### ISSUE TITLE
bdo_npe.exe not working.

### ISSUE THREAD

**Issue by 6monthpeek** [MoQtip/bdo-NPE#2]
Hello there,
I did certUtil and run at administrator. I'm still not seeing any result on my screen. I checked task manager but i failed to find anything.

**Comment by MoQtip** [comment]
Hi @6monthpeek,

Thank you for reaching out. I'm sorry to hear you're experiencing issues with bdo_npe.exe. To better assist you, could you provide a bit more detail on the following:

- The exact command you ran with certUtil.
- Any error messages or logs that were generated.
- Your operating system and version.

This information will help me diagnose the problem more effectively. In the meantime, ensure that all prerequisites listed in the README are installed and up to date.

Looking forward to your response!

Best,
MoQtip

**Comment by MoQtip** [comment]
Hi **@6monthpeek**,

I hope this message finds you well. **I wanted to extend a heartfelt thank you** for your valuable contribution in reporting the issue with `bdo_npe.exe` not working. Your report helped me identify and resolve the path resolution problems that were affecting the executable.

I sincerely apologize for the wait time in addressing this issue. Your patience and understanding have been greatly appreciated. The fix has been implemented in the latest release (v1.1.0), and I am confident that it resolves the problems you encountered.

If you have any further questions, suggestions, or encounter any other issues, please do not hesitate to reach out. Your feedback is incredibly important to me, and I am committed to ensuring a smooth and efficient experience for all users.

Thank you once again for your support and contribution to improving *BDO NodePath Explorer (NPE)*.

Best regards,
@MoQtip
